
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.FileChooserButton FileChooser;
	
	private global::Gtk.HBox hbox20;
	
	private global::Gtk.ComboBox SerieComboBox;
	
	private global::Gtk.SpinButton CountSpinbutton;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.Label ProgressLabel;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button GenButton;
	
	private global::Gtk.Button InfoButton;
	
	private global::Gtk.Button CloseButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Kenteken generator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.FileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.FileChooser.Name = "FileChooser";
		this.table3.Add (this.FileChooser);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.FileChooser]));
		w1.TopAttach = ((uint)(1));
		w1.BottomAttach = ((uint)(2));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.hbox20 = new global::Gtk.HBox ();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.SerieComboBox = global::Gtk.ComboBox.NewText ();
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 1"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 2"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 3"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 4"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 5"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 6"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 7"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 8"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 9"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 10"));
		this.SerieComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Serie 11"));
		this.SerieComboBox.Name = "SerieComboBox";
		this.hbox20.Add (this.SerieComboBox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.SerieComboBox]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.CountSpinbutton = new global::Gtk.SpinButton (0, 50000, 1);
		this.CountSpinbutton.CanFocus = true;
		this.CountSpinbutton.Name = "CountSpinbutton";
		this.CountSpinbutton.Adjustment.PageIncrement = 10;
		this.CountSpinbutton.ClimbRate = 1;
		this.CountSpinbutton.Numeric = true;
		this.hbox20.Add (this.CountSpinbutton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.CountSpinbutton]));
		w3.Position = 1;
		this.table3.Add (this.hbox20);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.hbox20]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("   Bestand");
		this.label10.UseUnderline = true;
		this.label10.Justify = ((global::Gtk.Justification)(2));
		this.table3.Add (this.label10);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("   Serie en aantal");
		this.label9.Justify = ((global::Gtk.Justification)(2));
		this.table3.Add (this.label9);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.label9]));
		w6.XOptions = ((global::Gtk.AttachOptions)(0));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
		w7.Position = 0;
		w7.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.ProgressLabel = new global::Gtk.Label ();
		this.ProgressLabel.Name = "ProgressLabel";
		this.ProgressLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
		this.alignment1.Add (this.ProgressLabel);
		this.vbox1.Add (this.alignment1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
		w9.Position = 1;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GenButton = new global::Gtk.Button ();
		this.GenButton.CanFocus = true;
		this.GenButton.Name = "GenButton";
		this.GenButton.UseUnderline = true;
		this.GenButton.Label = global::Mono.Unix.Catalog.GetString ("Genereer");
		this.hbox1.Add (this.GenButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GenButton]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.InfoButton = new global::Gtk.Button ();
		this.InfoButton.CanFocus = true;
		this.InfoButton.Name = "InfoButton";
		this.InfoButton.UseUnderline = true;
		this.InfoButton.Label = global::Mono.Unix.Catalog.GetString ("Toon info");
		this.hbox1.Add (this.InfoButton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.InfoButton]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.CloseButton = new global::Gtk.Button ();
		this.CloseButton.CanFocus = true;
		this.CloseButton.Name = "CloseButton";
		this.CloseButton.UseUnderline = true;
		this.CloseButton.Label = global::Mono.Unix.Catalog.GetString ("Sluiten");
		this.hbox1.Add (this.CloseButton);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.CloseButton]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.GenButton.Clicked += new global::System.EventHandler (this.OnGenButtonClicked);
		this.CloseButton.Clicked += new global::System.EventHandler (this.OnCloseButtonClicked);
	}
}
